### ISSUE TITLE
Unexpected token in Else-Statement

### ISSUE THREAD

**Issue by NotoriousRebel** [neolithos/neolua#115]
NeoLua Version:

1.3.11

Example to reproduce:
```Lua
local sys = clr.System;
local temp = {};
local hex = "68656c6c6f20776f726c64";
print("temp is created doing for loop");
for i=1, string.len(hex) do
      if ( math.fmod(hex[i], 2) == 0 ) then
              temp[i] = string.byte(string.sub(hex[i], 2), 16);
      end
end
```
Here is the full stack trace:
```
An exception has occurred: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Neo.IronLua.LuaParseException: Unexpected token in Else-Statement
   at Neo.IronLua.Parser.ParseElseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseIfStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseBlock(Scope scope, ILuaLexer code, Boolean activateRethrow)
   at Neo.IronLua.Parser.ParseRepeatLoop(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseStatement(Scope scope, ILuaLexer code)
   at Neo.IronLua.Parser.ParseBlock(Scope scope, ILuaLexer code, Boolean activateRethrow)
   at Neo.IronLua.Parser.ParseChunk(Lua runtime, LuaCompileOptions options, Boolean hasEnvironment, ILuaLexer code, Type typeDelegate, Type returnType, IEnumerable`1 args)
   at Neo.IronLua.Lua.CompileChunkCore(ILuaLexer lex, LuaCompileOptions options, IEnumerable`1 args)
   at Neo.IronLua.Lua.CompileChunk(String code, String name, LuaCompileOptions options, KeyValuePair`2[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Program.Main(String[] args) in C:\Program.cs:line 147
```

68656c6c6f20776f726c64 = Hello World
Things I have tried doing:

1. Empty else 
2. save fmod result to variable and compare that

This project is pretty amazing btw! Thank you for all the hard work you put it into it.

**Comment by neolithos** [comment]
Thank you. But I can not reproduce you exception.

Please, double check you example.

**Comment by NotoriousRebel** [comment]
I resolved the issue by changing how the byte array was created might've been a typo not 100% sure. Out of curiosity, let's say I wanted to use P/invoked methods inside NeoLua, what would be the easiest way?

For example
```csharp
[System.Runtime.InteropServices.DllImport("user32.dll")]
        public static extern int MessageBoxA(
       IntPtr hWnd,
       String text,
       String caption,
       int options);
```
And calling it like so:
```MessageBoxA(IntPtr.Zero, "hello from B assembly", "from messagebox", 1);```
Would creating a static package with the class having those methods implemented by easiest, are there other ways?

**Comment by neolithos** [comment]
For PInvoke's you need a static class in compiled language.

So, this is the only way I know.

**Comment by NotoriousRebel** [comment]
So something like this?

```csharp
  public class Test
    {


        [System.Runtime.InteropServices.DllImport("user32.dll")]
        public static extern int MessageBoxA(
           IntPtr hWnd,
           String text,
           String caption,
           int options);

        public void Message()
        {
            MessageBoxA(IntPtr.Zero, "hello from B ssembly", "from messagebox", 1);
        }
        class Program
    {
        public static void Main()
        {
            Lua lua = new Lua();
            LuaGlobal g = new LuaGlobal(lua);
            g.RegisterPackage("test", typeof(Test));
            dynamic dg = lua.CreateEnvironment<LuaGlobal>();

            try
            {
                

                var source = @"
                    test.Message();
                ";
                var chunk = lua.CompileChunk(source, "test.lua", new LuaCompileOptions() { DebugEngine = null });
                Console.WriteLine(dg.dochunk(chunk));
            }
            catch (Exception e)
            {
                Console.WriteLine("Expception: {0}", e.Message);
                var d = LuaExceptionData.GetData(e); // get stack trace
                Console.WriteLine("StackTrace: {0}", d.FormatStackTrace(0, false));
            }
        }
    }
    }

```

However, this causes an error 
```
Expception: Object is nil.
StackTrace:  -- internal --
```

**Comment by neolithos** [comment]
`Message` should be a static method.

In your case, you could alternativly set an instance to the global variables.

```C#
dg.test = new Test();
```

**Comment by NotoriousRebel** [comment]
I changed the message method to be static; however, couldn't get it working :(.
On the bright side, doing it with a global variable and changing the method to not be static worked.

**Comment by neolithos** [comment]
It works with static:

```C#
    public class Test
    {


        [System.Runtime.InteropServices.DllImport("user32.dll")]
        public static extern int MessageBoxA(
           IntPtr hWnd,
           String text,
           String caption,
           int options);

        public static void Message()
        {
            MessageBoxA(IntPtr.Zero, "hello world!", "from messagebox", 1);
        }
        class Program
        {
            public static void Main()
            {
                Lua lua = new Lua();
                LuaGlobal g = new LuaGlobal(lua);
                g.RegisterPackage("test", typeof(Test));
                ILuaDebug debugEngine = LuaStackTraceDebugger.Default;
                try
                {


                    var source = @"
                    test.Message();
                ";
                    var chunk = lua.CompileChunk(source, "test.lua", new LuaCompileOptions() { DebugEngine = debugEngine });
                    Console.WriteLine(g.DoChunk(chunk));
                }
                catch (Exception e)
                {
                    Console.WriteLine("Expception: {0}", e.Message);
                    var d = LuaExceptionData.GetData(e); // get stack trace
                    Console.WriteLine("StackTrace: {0}", d.FormatStackTrace(0, false));
                }
            }
        }
    }
```

**Comment by NotoriousRebel** [comment]
ahh excellent thanks! Out of curiosity, do you know why changing this line: 
```
Lua lua = new Lua();
``` 

to

```
Dynamic lua = new Lua();
```
breaks things.

**Comment by neolithos** [comment]
Because the dynamic interface is a little bit different.
It is mainly the style of names, there different in C# and Lua.

**Comment by NotoriousRebel** [comment]
Thank you for the quick replies, I am using this for a project and have run into a roadblock, how to properly deal with structs?
Take your example:
```csharp

public class StructTest
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct DemoStruct
        {
            public IntPtr test;
         
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct TestStruct
        {
            public DemoStruct demo;
            public uint iSize;
            public string hello;
        }

        public TestStruct CreateStruct(string a, IntPtr ptr, uint c)
        {
            var mystruct = new TestStruct();
            mystruct.hello = a;
            mystruct.iSize = c;
            mystruct.demo = new DemoStruct
            {
                test = ptr,
            };
            return mystruct;
        }
    }

    class Program
    {
        public static void Main()
        {
            Lua lua = new Lua();
            LuaGlobal g = new LuaGlobal(lua);
            dynamic dg = lua.CreateEnvironment<LuaGlobal>();
            dg.StructTest = new StructTest();
           
            ILuaDebug debugEngine = LuaStackTraceDebugger.Default; 
            try
            {
                var source = @"
                    local sys = clr.System;
                    local ptr = sys.IntPtr(5);
                    local result = StructTest:CreateStruct(""hello world!"", ptr, 5);
                    print(""your result: "");
                    print(result);
                    print(""value of hello in struct: "");
                    print(result.hello);
                    print(""Changing of value of hello to foo bar"");
                    result.hello = ""foo bar!!"";
                    print(""Your new value is: "");
                    print(result.hello);
                ";
                var chunk = lua.CompileChunk(source, "test.lua", new LuaCompileOptions() { DebugEngine = debugEngine });
                Console.WriteLine(dg.dochunk(chunk));
            }
            catch (Exception e)
            {
                Console.WriteLine("Expception: {0}", e.Message);
                var d = LuaExceptionData.GetData(e); // get stack trace
                Console.WriteLine("StackTrace: {0}", d.FormatStackTrace(0, false));
            }
}
```
You would expect:
```
LuaLoaderTest.StructTest+TestStruct
value of hello in struct:
hello world!
Changing of value of hello to foo bar
Your new value is:
foo bar!!
```

However, what you get is:
```
your result:
LuaLoaderTest.StructTest+TestStruct
value of hello in struct:
hello world!
Changing of value of hello to foo bar
Your new value is:
hello world!
```
Also, am I creating IntPtrs correctly? They don't seem to be getting printed at all?
Should I be using cast?
```lua
 local sys = clr.System;
 local ptr = cast(sys.IntPtr, 5);
```

**Comment by neolithos** [comment]
It would be more structured if you create for every question a new issue. And close the answered.

1. I would expect the second result, because you create a lot box and unboxing operations. If you want to use structs, the only way is to use strongly typed variables.

2. `cast` ist defined to use a type as first parameter. So the correct way would be `cast(System.IntPtr, 5)`.

**Comment by NotoriousRebel** [comment]
Closing this as I have created a new issue and in regards to item #2 that worked.
