### ISSUE TITLE
string.format hex conversion throws error

### ISSUE THREAD

**Issue by scottharman** [neolithos/neolua#121]
NeoLua Version: 1.3.11

Converting an integer value into a range between 0x555 and 0xFFF, fails with 'format specifier was invalid'
If I leave the value between 0 and 255, with a 2 digit conversion, it works fine, but the moment I try a 3 digit (or 4 digit) hex conversion it fails - I'm unable to see at this point whether it's the AT.MIN.Tools formathex or sprintf causing the issue -

Ok... I'm getting closer.  

Example to reproduce:
```Lua
        elseif style == "HexRange" then
          val = round(tonumber(Value) * 27.3) + 1365
          Debug("Infodriver value before transform :" ..val) 
          score = string.format('%03X',tonumber(val))
```
Stacktrace:
```
9/10/2020 12:44:35 pm:SeriousError:CRITCAL ERROR:<Bold>Error Unhandled Exception:</Bold>Format specifier was invalid.
9/10/2020 12:44:35 pm:SeriousError:CRITCAL ERROR:<Bold>Trace:</Bold>   at System.Number.FormatDouble(Double value, String format, NumberFormatInfo info)
   at System.Double.ToString(String format, IFormatProvider provider)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at AT.MIN.Tools.FormatHex(String NativeFormat, Boolean Alternate, Int32 FieldLength, Int32 FieldPrecision, Boolean Left2Right, Char Padding, Object Value) in C:\Users\scott\Documents\GitHub\neolua\NeoLua\Extern\printf.cs:line 628
   at AT.MIN.Tools.sprintf(String Format, Object[] Parameters) in C:\Users\scott\Documents\GitHub\neolua\NeoLua\Extern\printf.cs:line 443
   at Neo.IronLua.LuaLibraryString.format(String formatstring, Object[] args) in C:\Users\scott\Documents\GitHub\neolua\NeoLua\LuaLibraries.cs:line 353
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

**Comment by neolithos** [comment]
`val` is a double and the .net `String.Format` does not like doubles at this point.

**Comment by scottharman** [comment]
Indeed, I've just spotted that, I was rounding to the nearest integer, and I did confirm that I was only passing in integers

I've confirmed that natively in lua, my test code with values in the range 0 - 100 did all work correctly, and were successfully rounded

I've added the following else if to 'printf.cs'
```printf.cs line 400
					else if (o is double)
						o = (long)Math.Round((double)o);
```
which has handled the edge case for my particular example

**Comment by neolithos** [comment]
It would be nice, if you check my changes. And let me know, if we need improvments. Or make a pull request.

**Comment by scottharman** [comment]
Just testing it now - appears to be successful but will confirm once I’ve run through my tests

**Comment by scottharman** [comment]
Confirmed the fix functions correctly 
I'll follow the same style and fork if I come across anything else in a similar vein
Many thanks

**Comment by neolithos** [comment]
You are welcome.
