### ISSUE TITLE
gmatch dies with "Can not call nil value." when called with empty string

### ISSUE THREAD

**Issue by chi-lambda** [neolithos/neolua#126]
NeoLua Version:

```csharp
using Neo.IronLua;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            using var lua = new Lua();
            dynamic env = lua.CreateEnvironment<LuaGlobal>();
            env.dochunk("for k,v in string.gmatch('', '.') do print(k,v) end", "test.lua");
        }
    }
} 
```

When called, the line with `dochunk` crashes with "Can not call nil value.". Stacktrace:

```
   at Neo.IronLua.LuaChunk.Run(LuaTable env, Object[] callArgs)
   at Neo.IronLua.LuaGlobal.DoChunk(LuaChunk chunk, Object[] callArgs)
   at Neo.IronLua.LuaGlobal.DoChunk(String code, String name, KeyValuePair`2[] args)
   at Neo.IronLua.LuaGlobal.LuaDoChunk(Object[] args)
   at CallSite.Target(Closure , CallSite , Object , String , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , Object , String , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Administrator\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 11
```

Calling it with a non-empty string (e.g. `string.gmatch('a', '.')`) works as expected and prints `a`.

Example to reproduce:

Calling the same line
```Lua
for k,v in string.gmatch('', '.') do print(k,v) end
```
in Lua results in no output (as expected).

I'll have a look at it over the weekend unless someone spots the issue immediately.

Incidentally, the error should say "Cannot" instead of "Can not".

**Comment by chi-lambda** [comment]
Pretty simple fix, as it turns out. `gmatch` returned `nil` but should return an empty iterator.

**Comment by neolithos** [comment]
Thx, for finding the bug and more important the fix.
