### ISSUE TITLE
Github version of NeoLua fails to detect function's overload.

### ISSUE THREAD

**Issue by pyrostrex** [neolithos/neolua#22]
Example:

```lua
local DirectoryInfo = clr.System.IO.DirectoryInfo;
local di = DirectoryInfo("Scripts");
local fi = di:GetFiles();
```

Returns an `ArgumentNullException`:

```
Value cannot be null.
Parameter name: searchPattern

at Neo.IronLua.LuaChunk.Run(LuaTable env, Object[] callArgs) in C:\neolua-master\NeoLua\LuaChunk.cs:line 64
at Neo.IronLua.LuaGlobalPortable.DoChunk(LuaChunk chunk, Object[] callArgs) in C:\neolua-master\NeoLua\LuaGlobalPortable.cs:line 167
at Neo.IronLua.LuaGlobalPortable.DoChunk(TextReader tr, String sName, KeyValuePair`2[] args) in C:\neolua-master\NeoLua\LuaGlobalPortable.cs:line 149
at Neo.IronLua.LuaGlobal.DoChunk(String sFileName, KeyValuePair`2[] args) in C:\neolua-master\NeoLuaD\LuaGlobal.cs:line 39
at ExternalXaml.Engine.LuaWindow.LuaCompile(String luaName) in C:\ExternalXaml\ExternalXaml\Engine\LuaWindow.vb:line 59
```

Note:

* It was working on the NuGet version of NeoLua
* Reproducable with my CodeProject's NeoLua implementation.

**Comment by neolithos** [comment]
Thx, for finding.
