### ISSUE TITLE
Cannot write file without close

### ISSUE THREAD

**Issue by xiaomiaozone** [neolithos/neolua#57]
NeoLua Version:  NeoCmd 5.3 (1.2.23.0)

I use it to output some text. but the output file is empty.
```Lua
file = io.open("test.txt", "w")
file:write("test")
-- no file:close()
```

**Comment by neolithos** [comment]
I use buffered streaming classes, so you must call `file:flush()` after the write if you want to persist the data immediately. Or you write more the 1024 bytes.

The `flush` should also be done sometimes later by the garbage collector, but not if the process get's stopped immediately.

**Comment by xiaomiaozone** [comment]
In my view, the object is destructed at the end of the process, should not automatically call close or flush?

**Comment by xiaomiaozone** [comment]
```
> local file = io.open ("test.txt", "w")
> file:write("test")
>
                                                                               ==> compile: 80 ms [196 byte] run: 45 ms
> :q

Runtime Error:  System.ObjectDisposedException: 
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at Neo.IronLua.LuaFile.flush()
   at Neo.IronLua.LuaFileStream.flush()
   at Neo.IronLua.LuaFile.Dispose(Boolean disposing)
   at Neo.IronLua.LuaFileStream.Dispose(Boolean disposing)
   at Neo.IronLua.LuaFile.Finalize()
```

**Comment by neolithos** [comment]
Thanks for reporting.
