### ISSUE TITLE
require() fails with "Could not find a part of the path"

### ISSUE THREAD

**Issue by thoj** [neolithos/neolua#87]
NeoLua Version: 1.3.2

Example to reproduce:
main.lua:
```Lua
require("test")
```
test.lua:
```Lua
print("ok")
```

This fails with this exception:
Could not find a part of the path 'C:\my\path\to\solution\project\bin\Debug\\%currentdirectory%\test.lua'.

What is the %currentdirectory% variable doing there?

dofile() seems to work fine.

**Comment by neolithos** [comment]
%currentdirectory% should be replaced with the current directory.
Do you have a full stack trace for me?

**Comment by thoj** [comment]
Stacktrace:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\my\path\to\solution\project\bin\Debug\%currentdirectory%\test.lua'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Neo.IronLua.Lua.CompileChunk(String fileName, LuaCompileOptions options, KeyValuePair`2[] args)
   at Neo.IronLua.LuaLibraryPackage.LuaRequire(LuaGlobal global, String moduleName)
   at Neo.IronLua.LuaGlobal.LuaRequire(Object modname)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at config.Update(Closure )
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at test.test.<>c__DisplayClass7_0.<ExecuteLua>b__0()
```

**Comment by neolithos** [comment]
Can you verify my fix?

**Comment by thoj** [comment]
Yes! This fixes the issue for me! 👍

**Comment by RussellHaley** [comment]
I'd love to see this fix get pushed to nuget. Cheers, Russ
